exclude_patterns = ["20*/**"]
test_patterns = [
  "tests/**,",
  "**/test*.py"
]
version = 1

[[analyzers]]
enabled = true
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"
skip_doc_coverage = ["module", "magic", "init", "class","nonpublic"]

[[analyzers]]
enabled = true
name = "test-coverage"

[[analyzers]]
enabled = true
name = "secrets"
