exclude_patterns = ["20*/**"]
test_patterns = [
  "**/test*.py",
  "tests/**,"
]
version = 1

[[analyzers]]
enabled = true
name = "python"

[analyzers.meta]
runtime_version = "3.x.x"
skip_doc_coverage = ["class", "init", "magic", "module", "nonpublic"]

[[analyzers]]
enabled = true
name = "test-coverage"

[[analyzers]]
enabled = true
name = "secrets"
