---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, pre-push]
repos                     :
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: debug-statements
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args: [--in-place]

  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter

#  - repo: https://github.com/markdownlint/markdownlint
#    rev: v0.12.0
#    hooks:
#      - id: markdownlint
#        args: [--style, cirosantilli, --rules, '~first-header-h1,~first-line-h1,~no-trailing-punctuation']

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
      - id: python-use-type-annotations
      - id: python-check-blanket-type-ignore
      - id: python-check-blanket-noqa

#  - repo: https://github.com/asottile/yesqa
#    rev: v1.4.0
#    hooks:
#      - id: yesqa
#        additional_dependencies: &flake8_deps
##          - flake8-annotations
#          - flake8-bandit
#          - flake8-broken-line
#          - flake8-bugbear
#          - flake8-builtins
#          - flake8-comprehensions
##          - flake8-docstrings
#          - flake8-eradicate
#          - flake8-logging-format
#          - flake8-markdown
##          - flake8-no-pep420
##          - flake8-quotes
#          - flake8-simplify
#          - flake8-tidy-imports
#          - flake8-type-checking
#          - flake8-typing-imports
#          - flake8-use-fstring
#          - pep8-naming

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py311-plus]

  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

#  - repo: https://github.com/pycqa/flake8
#    rev: 5.0.4
#    hooks:
#      - id: flake8
#        exclude: ^(20)
#        args: [--ignore, 'E203,E501,S101', --min-python-version, 3.9.0]
#        additional_dependencies: *flake8_deps

#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.910-1
#    hooks:
#      - id: mypy

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.3
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --colons, --width, '88']

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort
        args: [--all, --in-place]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.5
    hooks:
      - id: ruff

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: ['bandit[toml]']

  - repo: local
    hooks:
      - id: pytest
        stages: [pre-push]
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
