[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.black]
line-length = 88

[tool.isort]
line_length = 88
multi_line_output = 3
balanced_wrapping = true
atomic = true
lines_after_imports = 2
lines_between_types = 1
combine_star = true
include_trailing_comma = true
use_parentheses = true
known_first_party = "aoc"
known_third_party = []

[tool.poetry]
authors = ["NimVek <NimVek@users.noreply.github.com>"]
classifiers = [
    "Topic :: Education",
    "Intended Audience :: Education",
    "Environment :: Console",
    "Operating System :: OS Independent",
    "Natural Language :: English",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Development Status :: 3 - Alpha",
]
description = "Advent of Code Helper."
license = "GPL-3.0-or-later"
name = "aoc"
readme = "README.md"
repository = "https://github.com/NimVek/advent-of-code"
version = "21.11.0"

[tool.poetry.dependencies]
incremental = "^21.3.0"
python = "^3.9"
GitPython = "^3.1.24"
requests = "^2.26.0"
html2markdown = "^0.1.7"
beautifulsoup4 = "^4.10.0"

[tool.poetry.dev-dependencies]
ipython = "^7.29.0"
mypy = "^0.910"
pre-commit = "^2.15.0"
pytest = "^6.2.5"
pytest-cov = "^3.0.0"
pytest-randomly = "^3.10.2"
pytest-xdist = "^2.4.0"
toml-sort = "^0.19.0"
black = "^21.11b1"
toml = "^0.10.2"
types-toml = "^0.10.1"

[tool.poetry.scripts]
aoc = 'aoc.main:main'

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
]
