---
name: Code Scanning

on  :
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 24 8 * * 2

jobs:
  analyze:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        language: [python]

    name: Analyze
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Analyze
        uses: github/codeql-action/analyze@v2
